Added support for PostgreSQL/PostGIS extensions. At the same time cleaned up debian post install functions to correct report errors.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -6,11 +6,17 @@ SCRIPT=${0##*/}
 SUCCESS=0
 FAILURE=1
 
+clean_up()
+{
+    [ -f $TMPFILE ] && rm -f $TMPFILE
+}
+
 die()
 {
     msg=$1
     err_no=$2
     echo "$SCRIPT: $msg" 1>&2
+    clean_up
     exit ${err_no:-$FAILURE}
 }
 
@@ -25,6 +31,10 @@ DB=bde_db
 PG_SERVICE=postgresql
 PG_INIT=/etc/init.d/$PG_SERVICE
 USE_SERVICE=0
+HAS_POSTGIS_EXT=
+HAS_ADMIN_EXT=
+TMPFILE=`mktemp -t $LDS_PACKAGE.XXXXXX` || { echo "$0: Cannot create temporary file" >&2; exit 1;  }
+chmod 0777 $TMPFILE
 
 if [ -x /usr/sbin/service ]; then
     USE_SERVICE=1
@@ -54,43 +64,63 @@ if [ $rc -ne $SUCCESS ]; then
     fi
 fi
 
-# create bde database if it does not exists
-if ! su -l $PG_USER -c "psql --list | grep $DB"; then
-    su -l $PG_USER -c "createdb -O $PG_USER -E UTF8 -T template0 -l C $DB"
-    rc=$?
+PG_VERSION="$(su -l $PG_USER -c """psql -t -A postgres -c 'SHOW server_version_num'""")"
     
+# create bde database if it does not exists
+if ! su -l $PG_USER -c "psql -t -A --list | grep $DB"; then
+    rc=$(sudo su -l $PG_USER -c "createdb -O $PG_USER -E UTF8 -T template0 -l C $DB &> $TMPFILE; echo \$?")
     if [ $rc -ne $SUCCESS ] ; then
         die "Could not create database" $rc
     fi
     
-    su -l $PG_USER -c "createlang plperlu $DB"
-    rc=$?
+    rc=$(sudo su -l $PG_USER -c "createlang plperlu $DB &> $TMPFILE; echo \$?")
     if [ $rc -ne $SUCCESS ] ; then
         die "Could not install plperlu database language" $rc
     fi
     
-    su -l $PG_USER -c "createlang plperl $DB"
-    rc=$?
+    rc=$(sudo su -l $PG_USER -c "createlang plperl $DB &> $TMPFILE; echo \$?")
     if [ $rc -ne $SUCCESS ] ; then
         die "Could not install plperl database language" $rc
     fi
     
-    su -l $PG_USER -c "psql -d $PG_USER -f /usr/share/postgresql/9.0/contrib/adminpack.sql"
-    rc=$?
-    if [ $rc -ne $SUCCESS ] ; then
-        die "Could not install database admin pack" $rc
+    if [ $PG_VERSION -gt 90100 ]; then
+        HAS_POSTGIS_EXT="$(su -l $PG_USER -c """psql -t -A -c 'SELECT name FROM pg_available_extensions WHERE name = \$\$postgis\$\$' $PG_USER""")"
+        HAS_ADMIN_EXT="$(su -l $PG_USER -c """psql -t -A -c 'SELECT name FROM pg_available_extensions WHERE name = \$\$adminpack\$\$' $PG_USER""")"
     fi
     
-    su -l $PG_USER -c "psql -d $DB -f /usr/share/postgresql/9.0/contrib/postgis-1.5/postgis.sql"
-    rc=$?
-    if [ $rc -ne $SUCCESS ] ; then
-        die "Could install postgis functions" $rc
+    if [ -n "$HAS_ADMIN_EXT" ]; then
+        rc=$(sudo su -l $PG_USER -c "psql -d $DB -c 'CREATE EXTENSION adminpack' &> $TMPFILE; echo \$?")
+        if [ $rc -ne $SUCCESS ] ; then
+            die "Could install adminpack functions" $rc
+        fi
+    else
+        PG_ADMINPACK=/usr/share/postgresql/9.0/contrib/adminpack.sql
+        if [ -f $PG_ADMINPACK ]; then
+            rc=$(sudo su -l $PG_USER -c "psql -v ON_ERROR_STOP=TRUE -d $DB -f $PG_ADMINPACK &> $TMPFILE; echo \$?")
+            if [ $rc -ne $SUCCESS ] ; then
+                die "Could not install database admin pack" $rc
+            fi
+        fi
     fi
     
-    su -l $PG_USER -c "psql -d $DB -f /usr/share/postgresql/9.0/contrib/postgis-1.5/spatial_ref_sys.sql"
-    rc=$?
-    if [ $rc -ne $SUCCESS ] ; then
-        die "Could install postgis SRS data" $rc
+    if [ -n "$HAS_POSTGIS_EXT" ]; then
+        rc=$(sudo su -l $PG_USER -c "psql -d $DB -c 'CREATE EXTENSION postgis' &> $TMPFILE; echo \$?")
+        if [ $rc -ne $SUCCESS ] ; then
+            die "Could install postgis functions" $rc
+        fi
+    else
+        # install postgis 1.5
+        POSTGIS_INSTALL_FILE=/usr/share/postgresql/9.0/contrib/postgis-1.5/postgis.sql
+        rc=$(sudo su -l $PG_USER -c "psql -v ON_ERROR_STOP=TRUE -d $DB -f $POSTGIS_INSTALL_FILE &> $TMPFILE; echo \$?")
+        if [ $rc -ne $SUCCESS ] ; then
+            die "Could install postgis functions" $rc
+        fi
+        
+        POSTGIS_SRS_FILE=/usr/share/postgresql/9.0/contrib/postgis-1.5/postgis.sql
+        rc=$(sudo su -l $PG_USER -c "psql -v ON_ERROR_STOP=TRUE -d $DB -f $POSTGIS_SRS_FILE &> $TMPFILE; echo \$?")
+        if [ $rc -ne $SUCCESS ] ; then
+            die "Could install postgis SRS data" $rc
+        fi
     fi
 fi
 
@@ -98,15 +128,15 @@ fi
 SQL_FILES="
     $LDS_SHARE_DIR/sql/bde_roles.sql
     $LDS_SHARE_DIR/sql/bde_schema.sql
-    $LDS_SHARE_DIR/sql/bde_ext_schema.sql
     $LDS_SHARE_DIR/sql/bde_functions.sql
-    $LDS_SHARE_DIR/sql/bde_ext_functions.sql
     $LDS_SHARE_DIR/sql/table_version_tables.sql
     $LDS_SHARE_DIR/sql/table_version_functions.sql
     $LDS_SHARE_DIR/sql/bde_control_tables.sql
     $LDS_SHARE_DIR/sql/bde_control_functions.sql
     $LDS_SHARE_DIR/sql/lds_layer_tables.sql
     $LDS_SHARE_DIR/sql/lds_layer_functions.sql
+    $LDS_SHARE_DIR/sql/bde_ext_schema.sql
+    $LDS_SHARE_DIR/sql/bde_ext_functions.sql
     $LDS_SHARE_DIR/sql/create_table_polygon_grid.sql
     $LDS_SHARE_DIR/sql/patch_management.sql
     $LDS_SHARE_DIR/sql/patches.sql
@@ -114,10 +144,10 @@ SQL_FILES="
 
 for SQL_FILE in $SQL_FILES
 do
-    su -l $PG_USER -c "psql -d $DB -f $SQL_FILE"
-    rc=$?
+    rc=$(sudo su -l $PG_USER -c "psql -v ON_ERROR_STOP=TRUE -d $DB -f $SQL_FILE &> $TMPFILE; echo \$?")
     if [ $rc -ne $SUCCESS ] ; then
-        die "Could install SQL file: $SQL_FILE" $rc
+        cat $TMPFILE
+        die "Couldn't install SQL file: $SQL_FILE" $rc
     fi
 done
 
@@ -149,6 +179,8 @@ if [ ! -d $LDS_LOG_DIR ]; then
 fi
 chown -R $LDS_USER:adm $LDS_LOG_DIR;
 chmod 0755 $LDS_LOG_DIR;
+
+clean_up
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
